from __future__ import annotations

from pathlib import Path
from typing import Any

from stageq.model.runtime import QRuntimeConfig
from stageq.model.service import ResolvedServiceConfig


def _q_atom(value: Any) -> str:
    if value is None:
        return "::"
    if isinstance(value, bool):
        return "1b" if value else "0b"
    if isinstance(value, int):
        return str(value)
    if isinstance(value, float):
        return f"{value}f"
    if isinstance(value, str):
        escaped = value.replace("\\", "\\\\").replace('"', '\\"')
        return f'"{escaped}"'
    raise TypeError(f"unsupported scalar type: {type(value)!r}")


def _to_q(value: Any) -> str:
    if isinstance(value, (str, int, float, bool)) or value is None:
        return _q_atom(value)

    if isinstance(value, list):
        if not value:
            return "()"
        return "(" + ";".join(_to_q(v) for v in value) + ")"

    if isinstance(value, dict):
        if not value:
            return "()!()"
        keys = list(value.keys())
        key_expr = "`" + "`".join(str(k) for k in keys)
        val_expr = "(" + ";".join(_to_q(value[k]) for k in keys) + ")"
        return f"{key_expr}!{val_expr}"

    raise TypeError(f"unsupported config type: {type(value)!r}")


def render_config_q(cfg: ResolvedServiceConfig) -> str:
    if not isinstance(cfg.runtime, QRuntimeConfig):
        raise ValueError("render_config_q only supports q runtime")

    meta = {
        "name": cfg.identity.name,
        "type": cfg.identity.service_type,
        "env": cfg.identity.env_name,
        "instance_id": cfg.identity.instance_id,
    }
    libs = [str(p) for p in cfg.runtime.bootstrap.libraries] if cfg.runtime.bootstrap else []

    lines = [
        "/ generated by stageqsvc",
        ".stageq:()",
        f".stageq.meta:{_to_q(meta)}",
        f".stageq.cfg:{_to_q(cfg.service_config)}",
        f".stageq.libs:{_to_q(libs)}",
        "",
    ]
    return "\n".join(lines)


def write_config_q(cfg: ResolvedServiceConfig) -> Path:
    out = cfg.launch.generated_dir / f"{cfg.identity.name}.config.q"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(render_config_q(cfg), encoding="utf-8")
    return out
